# coding: utf-8

"""
    DagsHub API

    This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training.   # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dagshub_api
from dagshub_api.api.user_api import UserApi  # noqa: E501
from dagshub_api.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_authenticated_user(self):
        """Test case for get_authenticated_user

        Get authenticated user information  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get information about a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
