# coding: utf-8

"""
    DagsHub API

    The api docs are made with SwaggerUI using the OpenAPI 3 specification.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dagshub-api
from dagshub-api.models.issue import Issue  # noqa: E501
from dagshub-api.rest import ApiException


class TestIssue(unittest.TestCase):
    """Issue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssue(self):
        """Test Issue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dagshub-api.models.issue.Issue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
