# coding: utf-8

"""
    DagsHub API

    The api docs are made with SwaggerUI using the OpenAPI 3 specification.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dagshub_api
from dagshub_api.models.webhook_config import WebhookConfig  # noqa: E501
from dagshub_api.rest import ApiException


class TestWebhookConfig(unittest.TestCase):
    """WebhookConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookConfig(self):
        """Test WebhookConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dagshub_api.models.webhook_config.WebhookConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
