# DagsHub API
#
# The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
#
# OpenAPI spec version: 0.1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Issues Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Issues <- R6::R6Class(
  'Issues',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      IssuesObject <- list()

      IssuesObject
    },
    fromJSON = function(IssuesJson) {
      IssuesObject <- jsonlite::fromJSON(IssuesJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(IssuesJson) {
      IssuesObject <- jsonlite::fromJSON(IssuesJson)
    }
  )
)
