/* 
 * DagsHub API
 *
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dagshub_api.Api;
using dagshub_api.Model;
using dagshub_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dagshub_api.Test
{
    /// <summary>
    ///  Class for testing ExperimentKeys
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExperimentKeysTests
    {
        // TODO uncomment below to declare an instance variable for ExperimentKeys
        //private ExperimentKeys instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExperimentKeys
            //instance = new ExperimentKeys();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExperimentKeys
        /// </summary>
        [Test]
        public void ExperimentKeysInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExperimentKeys
            //Assert.IsInstanceOfType<ExperimentKeys> (instance, "variable 'instance' is a ExperimentKeys");
        }


        /// <summary>
        /// Test the property '_ExperimentKeys'
        /// </summary>
        [Test]
        public void _ExperimentKeysTest()
        {
            // TODO unit test for the property '_ExperimentKeys'
        }

    }

}
