/* 
 * DagsHub API
 *
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dagshub_api.Api;
using dagshub_api.Model;
using dagshub_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dagshub_api.Test
{
    /// <summary>
    ///  Class for testing PostIssue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostIssueTests
    {
        // TODO uncomment below to declare an instance variable for PostIssue
        //private PostIssue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PostIssue
            //instance = new PostIssue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PostIssue
        /// </summary>
        [Test]
        public void PostIssueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostIssue
            //Assert.IsInstanceOfType<PostIssue> (instance, "variable 'instance' is a PostIssue");
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Test]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }
        /// <summary>
        /// Test the property 'Milestone'
        /// </summary>
        [Test]
        public void MilestoneTest()
        {
            // TODO unit test for the property 'Milestone'
        }
        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Test]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
        /// <summary>
        /// Test the property 'Closed'
        /// </summary>
        [Test]
        public void ClosedTest()
        {
            // TODO unit test for the property 'Closed'
        }

    }

}
