/*
 * DagsHub API
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {User} from './User';

/**
 * The LabelStudioProjectAccess model module.
 * @module model/LabelStudioProjectAccess
 * @version 1.0.3
 */
export class LabelStudioProjectAccess {
  /**
   * Constructs a new <code>LabelStudioProjectAccess</code>.
   * @alias module:model/LabelStudioProjectAccess
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LabelStudioProjectAccess</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabelStudioProjectAccess} obj Optional instance to populate.
   * @return {module:model/LabelStudioProjectAccess} The populated <code>LabelStudioProjectAccess</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LabelStudioProjectAccess();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('repo_id'))
        obj.repoId = ApiClient.convertToType(data['repo_id'], 'Number');
      if (data.hasOwnProperty('project_id'))
        obj.projectId = ApiClient.convertToType(data['project_id'], 'Number');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('team_id'))
        obj.teamId = ApiClient.convertToType(data['team_id'], 'Number');
      if (data.hasOwnProperty('access_level'))
        obj.accessLevel = ApiClient.convertToType(data['access_level'], 'String');
      if (data.hasOwnProperty('created_unix'))
        obj.createdUnix = ApiClient.convertToType(data['created_unix'], 'Number');
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
LabelStudioProjectAccess.prototype.id = undefined;

/**
 * @member {Number} repoId
 */
LabelStudioProjectAccess.prototype.repoId = undefined;

/**
 * Project ID, -1 means wildcard access to all projects
 * @member {Number} projectId
 */
LabelStudioProjectAccess.prototype.projectId = undefined;

/**
 * User ID (present for user access entries)
 * @member {Number} userId
 */
LabelStudioProjectAccess.prototype.userId = undefined;

/**
 * Team ID (present for team access entries)
 * @member {Number} teamId
 */
LabelStudioProjectAccess.prototype.teamId = undefined;

/**
 * Allowed values for the <code>accessLevel</code> property.
 * @enum {String}
 * @readonly
 */
LabelStudioProjectAccess.AccessLevelEnum = {
  /**
   * value: "none"
   * @const
   */
  none: "none",

  /**
   * value: "annotator"
   * @const
   */
  annotator: "annotator"
};
/**
 * @member {module:model/LabelStudioProjectAccess.AccessLevelEnum} accessLevel
 */
LabelStudioProjectAccess.prototype.accessLevel = undefined;

/**
 * @member {Number} createdUnix
 */
LabelStudioProjectAccess.prototype.createdUnix = undefined;

/**
 * @member {module:model/User} user
 */
LabelStudioProjectAccess.prototype.user = undefined;

