/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param config 
 * @param events 
 * @param active Weather the hook is actually triggered on pushes or not. Ignore this field to leave it unchanged.
 */
case class HooksIdBody (
  config: Option[WebhookConfig] = None,
  events: Option[WebhookEvents] = None,
  active: Option[Boolean] = None
)

