/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param id 
 * @param title 
 * @param description 
 * @param state 
 * @param openIssues 
 * @param closedIssues 
 * @param closedAt 
 * @param dueOn 
 */
case class IssueMilestone (
  id: Option[Integer] = None,
  title: Option[String] = None,
  description: Option[String] = None,
  state: Option[String] = None,
  openIssues: Option[Integer] = None,
  closedIssues: Option[Integer] = None,
  closedAt: Option[String] = None,
  dueOn: Option[String] = None
)

