/**
 * DagsHub API
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * Key/value pairs to provide settings for this hook
 *
 * @param url A string defining the URL to which the payloads will be delivered. for example: '''http://yourwebsite.io'''
 * @param `contentType` A string defining the media type used to serialize the payloads. for example: '''json'''
 * @param secret An optional string that's passed with the HTTP requests body. for example: '''supersecretkey'''
 */
case class WebhookConfig (
  url: String,
  `contentType`: String,
  secret: Option[String] = None
)

