/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * Key/value pairs to provide settings for this hook
 *
 * @param url A string defining the URL to which the payloads will be delivered. for example: '''http://yourwebsite.io'''
 * @param `contentType` A string defining the media type used to serialize the payloads. for example: '''json'''
 * @param secret An optional string that's passed with the HTTP requests body. for example: '''supersecretkey'''
 */
case class WebhookConfig (
  url: String,
  `contentType`: String,
  secret: Option[String] = None
)

