/*
 * DagsHub API
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {GrantLabelStudioAccess} from '../model/GrantLabelStudioAccess';
import {InlineResponse200} from '../model/InlineResponse200';
import {LabelStudioProjectAccess} from '../model/LabelStudioProjectAccess';

/**
* Annotations service.
* @module api/AnnotationsApi
* @version 1.0.3
*/
export class AnnotationsApi {

    /**
    * Constructs a new AnnotationsApi. 
    * @alias module:api/AnnotationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getLabelStudioTeamAccess operation.
     * @callback moduleapi/AnnotationsApi~getLabelStudioTeamAccessCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LabelStudioProjectAccess{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get team access level for annotation projects
     * Get the access level for a specific team and project (or all projects)
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Number} teamid Team ID
     * @param {Object} opts Optional parameters
     * @param {Number} opts.projectId Label Studio project ID to filter by. If not specified, returns access for all projects. Use -1 for wildcard access.
     * @param {module:api/AnnotationsApi~getLabelStudioTeamAccessCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getLabelStudioTeamAccess(owner, repo, teamid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling getLabelStudioTeamAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getLabelStudioTeamAccess");
      }
      // verify the required parameter 'teamid' is set
      if (teamid === undefined || teamid === null) {
        throw new Error("Missing the required parameter 'teamid' when calling getLabelStudioTeamAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo,'teamid': teamid
      };
      let queryParams = {
        'project_id': opts['projectId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LabelStudioProjectAccess;

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/teams/{teamid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getLabelStudioUserAccess operation.
     * @callback moduleapi/AnnotationsApi~getLabelStudioUserAccessCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get user access level for annotation projects
     * Get the access level for a specific user and project (or all projects)
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Number} userid User ID
     * @param {Object} opts Optional parameters
     * @param {Number} opts.projectId Label Studio project ID to filter by. If not specified, returns access for all projects. Use -1 for wildcard access.
     * @param {module:api/AnnotationsApi~getLabelStudioUserAccessCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getLabelStudioUserAccess(owner, repo, userid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling getLabelStudioUserAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getLabelStudioUserAccess");
      }
      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling getLabelStudioUserAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo,'userid': userid
      };
      let queryParams = {
        'project_id': opts['projectId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/users/{userid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the grantLabelStudioTeamAccess operation.
     * @callback moduleapi/AnnotationsApi~grantLabelStudioTeamAccessCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Grant team access to annotation projects
     * Grant a team access to specific Label Studio annotation projects (organization repositories only)
     * @param {module:model/GrantLabelStudioAccess} body 
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Number} teamid Team ID
     * @param {module:api/AnnotationsApi~grantLabelStudioTeamAccessCallback} callback The callback function, accepting three arguments: error, data, response
     */
    grantLabelStudioTeamAccess(body, owner, repo, teamid, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling grantLabelStudioTeamAccess");
      }
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling grantLabelStudioTeamAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling grantLabelStudioTeamAccess");
      }
      // verify the required parameter 'teamid' is set
      if (teamid === undefined || teamid === null) {
        throw new Error("Missing the required parameter 'teamid' when calling grantLabelStudioTeamAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo,'teamid': teamid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/teams/{teamid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the grantLabelStudioUserAccess operation.
     * @callback moduleapi/AnnotationsApi~grantLabelStudioUserAccessCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Grant user access to annotation projects
     * Grant a user access to specific Label Studio annotation projects. User must be an organization member if the repo is owned by an organization.
     * @param {module:model/GrantLabelStudioAccess} body 
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Number} userid User ID
     * @param {module:api/AnnotationsApi~grantLabelStudioUserAccessCallback} callback The callback function, accepting three arguments: error, data, response
     */
    grantLabelStudioUserAccess(body, owner, repo, userid, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling grantLabelStudioUserAccess");
      }
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling grantLabelStudioUserAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling grantLabelStudioUserAccess");
      }
      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling grantLabelStudioUserAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo,'userid': userid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/users/{userid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listLabelStudioTeamAccess operation.
     * @callback moduleapi/AnnotationsApi~listLabelStudioTeamAccessCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/LabelStudioProjectAccess>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List team access entries for annotation projects
     * Get a list of teams with access to Label Studio annotation projects in the repository (organization repositories only)
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Object} opts Optional parameters
     * @param {Number} opts.projectId Label Studio project ID to filter by. If not specified, returns access for all projects. Use -1 for wildcard access.
     * @param {module:api/AnnotationsApi~listLabelStudioTeamAccessCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listLabelStudioTeamAccess(owner, repo, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling listLabelStudioTeamAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling listLabelStudioTeamAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo
      };
      let queryParams = {
        'project_id': opts['projectId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [LabelStudioProjectAccess];

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/teams', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listLabelStudioUserAccess operation.
     * @callback moduleapi/AnnotationsApi~listLabelStudioUserAccessCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/LabelStudioProjectAccess>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List user access entries for annotation projects
     * Get a list of users with access to Label Studio annotation projects in the repository
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Object} opts Optional parameters
     * @param {Number} opts.projectId Label Studio project ID to filter by. If not specified, returns access for all projects. Use -1 for wildcard access.
     * @param {module:api/AnnotationsApi~listLabelStudioUserAccessCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listLabelStudioUserAccess(owner, repo, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling listLabelStudioUserAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling listLabelStudioUserAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo
      };
      let queryParams = {
        'project_id': opts['projectId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [LabelStudioProjectAccess];

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the revokeLabelStudioTeamAccess operation.
     * @callback moduleapi/AnnotationsApi~revokeLabelStudioTeamAccessCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Revoke team access to annotation projects
     * Revoke a team&#x27;s access to Label Studio annotation projects
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Number} teamid Team ID
     * @param {Object} opts Optional parameters
     * @param {Number} opts.projectId Label Studio project ID to filter by. If not specified, returns access for all projects. Use -1 for wildcard access.
     * @param {module:api/AnnotationsApi~revokeLabelStudioTeamAccessCallback} callback The callback function, accepting three arguments: error, data, response
     */
    revokeLabelStudioTeamAccess(owner, repo, teamid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling revokeLabelStudioTeamAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling revokeLabelStudioTeamAccess");
      }
      // verify the required parameter 'teamid' is set
      if (teamid === undefined || teamid === null) {
        throw new Error("Missing the required parameter 'teamid' when calling revokeLabelStudioTeamAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo,'teamid': teamid
      };
      let queryParams = {
        'project_id': opts['projectId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/teams/{teamid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the revokeLabelStudioUserAccess operation.
     * @callback moduleapi/AnnotationsApi~revokeLabelStudioUserAccessCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Revoke user access to annotation projects
     * Revoke a user&#x27;s access to Label Studio annotation projects
     * @param {String} owner owner of the repository
     * @param {String} repo name of the repository
     * @param {Number} userid User ID
     * @param {Object} opts Optional parameters
     * @param {Number} opts.projectId Label Studio project ID to filter by. If not specified, returns access for all projects. Use -1 for wildcard access.
     * @param {module:api/AnnotationsApi~revokeLabelStudioUserAccessCallback} callback The callback function, accepting three arguments: error, data, response
     */
    revokeLabelStudioUserAccess(owner, repo, userid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'owner' is set
      if (owner === undefined || owner === null) {
        throw new Error("Missing the required parameter 'owner' when calling revokeLabelStudioUserAccess");
      }
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling revokeLabelStudioUserAccess");
      }
      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling revokeLabelStudioUserAccess");
      }

      let pathParams = {
        'owner': owner,'repo': repo,'userid': userid
      };
      let queryParams = {
        'project_id': opts['projectId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth', 'tokenAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/repos/{owner}/{repo}/annotations/access/users/{userid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}