/*
 * DagsHub API
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateAnnotatorTeam;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OrganizationsApi
 */
@Ignore
public class OrganizationsApiTest {

    private final OrganizationsApi api = new OrganizationsApi();

    /**
     * Create an organization team
     *
     * Create a new team in an organization. Use team_type \&quot;annotator\&quot; to create an annotator team with access only to annotation projects.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createOrgTeamTest() throws Exception {
        CreateAnnotatorTeam body = null;
        String orgname = null;
        api.createOrgTeam(body, orgname);

        // TODO: test validations
    }
}
