/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param name name of the repository
 * @param description A short description of the repository
 * @param &#x60;private&#x60; Either true to create a private repository, or false to create a public one.
 * @param autoInit Pass true to create an initial commit with README, .gitignore and LICENSE.
 * @param gitignores Desired language .gitignore templates to apply. Use the name of the templates.
 * @param license Desired LICENSE template to apply. Use the name of the template.
 * @param readme Desired README template to apply. Use the name of the template.
 */
data class CreateRepo (

    /* name of the repository */
    val name: kotlin.String,
    /* A short description of the repository */
    val description: kotlin.String? = null,
    /* Either true to create a private repository, or false to create a public one. */
    val `private`: kotlin.Boolean? = null,
    /* Pass true to create an initial commit with README, .gitignore and LICENSE. */
    val autoInit: kotlin.Boolean? = null,
    /* Desired language .gitignore templates to apply. Use the name of the templates. */
    val gitignores: kotlin.String? = null,
    /* Desired LICENSE template to apply. Use the name of the template. */
    val license: CreateRepo.License? = null,
    /* Desired README template to apply. Use the name of the template. */
    val readme: kotlin.String? = null
) {
    /**
    * Desired LICENSE template to apply. Use the name of the template.
    * Values: APACHE_LICENSE_2PERIOD0,MIT_LICENSE,ABSTYLES_LICENSE,ACADEMIC_FREE_LICENSE_V1PERIOD1,ACADEMIC_FREE_LICENSE_V1PERIOD2,ACADEMIC_FREE_LICENSE_V2PERIOD0,ACADEMIC_FREE_LICENSE_V2PERIOD1,ACADEMIC_FREE_LICENSE_V3PERIOD0,AFFERO_GENERAL_PUBLIC_LICENSE_V1PERIOD0,APACHE_LICENSE_1PERIOD0,APACHE_LICENSE_1PERIOD1,ARTISTIC_LICENSE_1PERIOD0,ARTISTIC_LICENSE_2PERIOD0,BSD_2CLAUSE_LICENSE,BSD_3CLAUSE_LICENSE,BSD_4CLAUSE_LICENSE,CREATIVE_COMMONS_CC0_1PERIOD0_UNIVERSAL,ECLIPSE_PUBLIC_LICENSE_1PERIOD0,EDUCATIONAL_COMMUNITY_LICENSE_V1PERIOD0,EDUCATIONAL_COMMUNITY_LICENSE_V2PERIOD0,GNU_AFFERO_GENERAL_PUBLIC_LICENSE_V3PERIOD0,GNU_FREE_DOCUMENTATION_LICENSE_V1PERIOD1,GNU_FREE_DOCUMENTATION_LICENSE_V1PERIOD2,GNU_FREE_DOCUMENTATION_LICENSE_V1PERIOD3,GNU_GENERAL_PUBLIC_LICENSE_V1PERIOD0,GNU_GENERAL_PUBLIC_LICENSE_V2PERIOD0,GNU_GENERAL_PUBLIC_LICENSE_V3PERIOD0,GNU_LESSER_GENERAL_PUBLIC_LICENSE_V2PERIOD1,GNU_LESSER_GENERAL_PUBLIC_LICENSE_V3PERIOD0,GNU_LIBRARY_GENERAL_PUBLIC_LICENSE_V2PERIOD0,ISC_LICENSE,MOZILLA_PUBLIC_LICENSE_1PERIOD0,MOZILLA_PUBLIC_LICENSE_1PERIOD1,MOZILLA_PUBLIC_LICENSE_2PERIOD03
    */
    enum class License(val value: kotlin.String){
        APACHE_LICENSE_2PERIOD0("Apache License 2.0"),
        MIT_LICENSE("MIT License"),
        ABSTYLES_LICENSE("Abstyles License"),
        ACADEMIC_FREE_LICENSE_V1PERIOD1("Academic Free License v1.1"),
        ACADEMIC_FREE_LICENSE_V1PERIOD2("Academic Free License v1.2"),
        ACADEMIC_FREE_LICENSE_V2PERIOD0("Academic Free License v2.0"),
        ACADEMIC_FREE_LICENSE_V2PERIOD1("Academic Free License v2.1"),
        ACADEMIC_FREE_LICENSE_V3PERIOD0("Academic Free License v3.0"),
        AFFERO_GENERAL_PUBLIC_LICENSE_V1PERIOD0("Affero General Public License v1.0"),
        APACHE_LICENSE_1PERIOD0("Apache License 1.0"),
        APACHE_LICENSE_1PERIOD1("Apache License 1.1"),
        ARTISTIC_LICENSE_1PERIOD0("Artistic License 1.0"),
        ARTISTIC_LICENSE_2PERIOD0("Artistic License 2.0"),
        BSD_2CLAUSE_LICENSE("BSD 2-clause License"),
        BSD_3CLAUSE_LICENSE("BSD 3-clause License"),
        BSD_4CLAUSE_LICENSE("BSD 4-clause License"),
        CREATIVE_COMMONS_CC0_1PERIOD0_UNIVERSAL("Creative Commons CC0 1.0 Universal"),
        ECLIPSE_PUBLIC_LICENSE_1PERIOD0("Eclipse Public License 1.0"),
        EDUCATIONAL_COMMUNITY_LICENSE_V1PERIOD0("Educational Community License v1.0"),
        EDUCATIONAL_COMMUNITY_LICENSE_V2PERIOD0("Educational Community License v2.0"),
        GNU_AFFERO_GENERAL_PUBLIC_LICENSE_V3PERIOD0("GNU Affero General Public License v3.0"),
        GNU_FREE_DOCUMENTATION_LICENSE_V1PERIOD1("GNU Free Documentation License v1.1"),
        GNU_FREE_DOCUMENTATION_LICENSE_V1PERIOD2("GNU Free Documentation License v1.2"),
        GNU_FREE_DOCUMENTATION_LICENSE_V1PERIOD3("GNU Free Documentation License v1.3"),
        GNU_GENERAL_PUBLIC_LICENSE_V1PERIOD0("GNU General Public License v1.0"),
        GNU_GENERAL_PUBLIC_LICENSE_V2PERIOD0("GNU General Public License v2.0"),
        GNU_GENERAL_PUBLIC_LICENSE_V3PERIOD0("GNU General Public License v3.0"),
        GNU_LESSER_GENERAL_PUBLIC_LICENSE_V2PERIOD1("GNU Lesser General Public License v2.1"),
        GNU_LESSER_GENERAL_PUBLIC_LICENSE_V3PERIOD0("GNU Lesser General Public License v3.0"),
        GNU_LIBRARY_GENERAL_PUBLIC_LICENSE_V2PERIOD0("GNU Library General Public License v2.0"),
        ISC_LICENSE("ISC license"),
        MOZILLA_PUBLIC_LICENSE_1PERIOD0("Mozilla Public License 1.0"),
        MOZILLA_PUBLIC_LICENSE_1PERIOD1("Mozilla Public License 1.1"),
        MOZILLA_PUBLIC_LICENSE_2PERIOD03("Mozilla Public License 2.03");
    }
}