//
// Closed.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Indicate initial issue state as closed (**true**) or open (**false**). */

public struct Closed: Codable {




}
