//
// ExperimentKeys.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExperimentKeys: Codable {

    public var experimentKeys: [String]

    public init(experimentKeys: [String]) {
        self.experimentKeys = experimentKeys
    }

    public enum CodingKeys: String, CodingKey { 
        case experimentKeys = "experiment_keys"
    }

}
