//
// File.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct File: Codable {

    public enum ModelType: String, Codable { 
        case file = "file"
        case dir = "dir"
    }
    public enum Versioning: String, Codable { 
        case git = "git"
        case dvc = "dvc"
        case bucket = "bucket"
    }
    public var path: String?
    public var type: ModelType?
    public var size: Int64?
    public var hash: String?
    public var versioning: Versioning?
    public var downloadUrl: String?
    public var contentUrl: String?

    public init(path: String? = nil, type: ModelType? = nil, size: Int64? = nil, hash: String? = nil, versioning: Versioning? = nil, downloadUrl: String? = nil, contentUrl: String? = nil) {
        self.path = path
        self.type = type
        self.size = size
        self.hash = hash
        self.versioning = versioning
        self.downloadUrl = downloadUrl
        self.contentUrl = contentUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case path
        case type
        case size
        case hash
        case versioning
        case downloadUrl = "download_url"
        case contentUrl = "content_url"
    }

}
