//
// Milestone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The **ID** of the milestone to associate this issue with.   **Note:** Only users with write access can set the milestone for new issues.  The milestone is silently dropped otherwise. */

public struct Milestone: Codable {




}
