//
// PostIssue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostIssue: Codable {

    public var title: ComponentsschemasTitleYaml?
    public var body: ComponentsschemasBodyYaml?
    public var assignee: ComponentsschemasAssigneeYaml?
    public var milestone: ComponentsschemasMilestoneYaml?
    public var labels: ComponentsschemasLabelsYaml?
    public var closed: ComponentsschemasClosedYaml?

    public init(title: ComponentsschemasTitleYaml? = nil, body: ComponentsschemasBodyYaml? = nil, assignee: ComponentsschemasAssigneeYaml? = nil, milestone: ComponentsschemasMilestoneYaml? = nil, labels: ComponentsschemasLabelsYaml? = nil, closed: ComponentsschemasClosedYaml? = nil) {
        self.title = title
        self.body = body
        self.assignee = assignee
        self.milestone = milestone
        self.labels = labels
        self.closed = closed
    }


}
