//
// WebhookEvents.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Determines what events the hook is triggered format. */
public typealias WebhookEvents = [String]