/* tslint:disable */
/* eslint-disable */
/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CollaboratorsCollaboratorBody
 */
export interface CollaboratorsCollaboratorBody {
    /**
     * The permission to grant the collaborator. Can be one of **read**, **write** and **admin**.
     * @type {string}
     * @memberof CollaboratorsCollaboratorBody
     */
    permission?: string;
}
