/* tslint:disable */
/* eslint-disable */
/**
 * DagsHub API
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    accessLevel?: InlineResponse200AccessLevelEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse200AccessLevelEnum {
    None = 'none',
    Annotator = 'annotator'
}

