/* tslint:disable */
/* eslint-disable */
/**
 * DagsHub API
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IntegrationInner
 */
export interface IntegrationInner {
    /**
     * Name/path of the bucket
     * @type {string}
     * @memberof IntegrationInner
     */
    name?: string;
    /**
     * Protocol used by the integration
     * @type {string}
     * @memberof IntegrationInner
     */
    protocol?: IntegrationInnerProtocolEnum;
    /**
     * URL to list the root of this bucket
     * @type {string}
     * @memberof IntegrationInner
     */
    listPath?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum IntegrationInnerProtocolEnum {
    S3 = 's3',
    Gs = 'gs'
}

