/* tslint:disable */
/* eslint-disable */
/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Body } from './body';
import { IssueAssignee } from './issue-assignee';
import { IssueLabels } from './issue-labels';
import { IssueMilestone } from './issue-milestone';
import { Title } from './title';
import { User } from './user';
/**
 * 
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    number?: number;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    user?: User;
    /**
     * 
     * @type {Title}
     * @memberof Issue
     */
    title: Title;
    /**
     * 
     * @type {Body}
     * @memberof Issue
     */
    body: Body;
    /**
     * 
     * @type {Array<IssueLabels>}
     * @memberof Issue
     */
    labels: Array<IssueLabels>;
    /**
     * 
     * @type {IssueMilestone}
     * @memberof Issue
     */
    milestone: IssueMilestone;
    /**
     * 
     * @type {IssueAssignee}
     * @memberof Issue
     */
    assignee: IssueAssignee;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    state?: string;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    comments?: number;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    updatedAt?: string;
    /**
     * 
     * @type {any}
     * @memberof Issue
     */
    pullRequest?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Issue
     */
    closed: boolean;
}
