/* tslint:disable */
/* eslint-disable */
/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Assignee } from './assignee';
import { Body } from './body';
import { Closed } from './closed';
import { Labels } from './labels';
import { Milestone } from './milestone';
import { Title } from './title';
/**
 * 
 * @export
 * @interface PostIssue
 */
export interface PostIssue {
    /**
     * 
     * @type {Title}
     * @memberof PostIssue
     */
    title?: Title;
    /**
     * 
     * @type {Body}
     * @memberof PostIssue
     */
    body?: Body;
    /**
     * 
     * @type {Assignee}
     * @memberof PostIssue
     */
    assignee?: Assignee;
    /**
     * 
     * @type {Milestone}
     * @memberof PostIssue
     */
    milestone?: Milestone;
    /**
     * 
     * @type {Labels}
     * @memberof PostIssue
     */
    labels?: Labels;
    /**
     * 
     * @type {Closed}
     * @memberof PostIssue
     */
    closed?: Closed;
}
