/* tslint:disable */
/* eslint-disable */
/**
 * DagsHub API
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WebhookConfig } from './webhook-config';
import { WebhookEvents } from './webhook-events';
/**
 * 
 * @export
 * @interface RepoHooksBody
 */
export interface RepoHooksBody {
    /**
     * The type of webhook
     * @type {string}
     * @memberof RepoHooksBody
     */
    type: RepoHooksBodyTypeEnum;
    /**
     * 
     * @type {WebhookConfig}
     * @memberof RepoHooksBody
     */
    config: WebhookConfig;
    /**
     * 
     * @type {WebhookEvents}
     * @memberof RepoHooksBody
     */
    events?: WebhookEvents;
}

/**
    * @export
    * @enum {string}
    */
export enum RepoHooksBodyTypeEnum {
    Dagshub = 'dagshub',
    Slack = 'slack',
    Discord = 'discord',
    Dingtalk = 'dingtalk'
}

