/*
 * DagsHub API
 *
 * The api docs are made with SwaggerUI using the OpenAPI 3 specification. 
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dagshub_api

type PostIssue struct {
	Title string `json:"title,omitempty"`
	Body string `json:"body,omitempty"`
	Assignee string `json:"assignee,omitempty"`
	Milestone int32 `json:"milestone,omitempty"`
	Labels *[]int32 `json:"labels,omitempty"`
	Closed bool `json:"closed,omitempty"`
}
