/*
 * DagsHub API
 *
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dagshub_api

type IntegrationInner struct {
	// Name/path of the bucket
	Name string `json:"name,omitempty"`
	// Protocol used by the integration
	Protocol string `json:"protocol,omitempty"`
	// URL to list the root of this bucket
	ListPath string `json:"list_path,omitempty"`
}
