/*
 * DagsHub API
 *
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dagshub_api

type MigrateRepo struct {
	// Remote Git address (HTTP/HTTPS URL or local path)
	CloneAddr string `json:"clone_addr"`
	// Authorization username
	AuthUsername string `json:"auth_username,omitempty"`
	// Authorization password
	AuthPassword string `json:"auth_password,omitempty"`
	// User ID who takes ownership of this repository
	UserId int32 `json:"user_id"`
	// Name of the repository
	RepoName string `json:"repo_name,omitempty"`
	// Repository will be a mirror (connected repository).
	Mirror bool `json:"mirror,omitempty"`
	// Repository will be private or public.
	Visibility string `json:"visibility,omitempty"`
	// Description of the repository
	Description string `json:"description,omitempty"`
}
