/*
 * DagsHub API
 *
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * API version: 1.0.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dagshub_api

type InlineResponse200 struct {
	UserId int64 `json:"user_id,omitempty"`
	ProjectId int64 `json:"project_id,omitempty"`
	AccessLevel string `json:"access_level,omitempty"`
}
