/* tslint:disable */
/* eslint-disable */
/**
 * DagsHub API
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CollaboratorsCollaboratorBody } from '../models';
/**
 * CollaboratorsApi - axios parameter creator
 * @export
 */
export const CollaboratorsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add user as a collaborator
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {string} collaborator collaborator username
         * @param {CollaboratorsCollaboratorBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCollaborator: async (owner: string, repo: string, collaborator: string, body?: CollaboratorsCollaboratorBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'owner' is not null or undefined
            if (owner === null || owner === undefined) {
                throw new RequiredError('owner','Required parameter owner was null or undefined when calling addCollaborator.');
            }
            // verify required parameter 'repo' is not null or undefined
            if (repo === null || repo === undefined) {
                throw new RequiredError('repo','Required parameter repo was null or undefined when calling addCollaborator.');
            }
            // verify required parameter 'collaborator' is not null or undefined
            if (collaborator === null || collaborator === undefined) {
                throw new RequiredError('collaborator','Required parameter collaborator was null or undefined when calling addCollaborator.');
            }
            const localVarPath = `/repos/{owner}/{repo}/collaborators/{collaborator}`
                .replace(`{${"owner"}}`, encodeURIComponent(String(owner)))
                .replace(`{${"repo"}}`, encodeURIComponent(String(repo)))
                .replace(`{${"collaborator"}}`, encodeURIComponent(String(collaborator)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required

            // authentication tokenAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get collaborators
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCollaborators: async (owner: string, repo: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'owner' is not null or undefined
            if (owner === null || owner === undefined) {
                throw new RequiredError('owner','Required parameter owner was null or undefined when calling getCollaborators.');
            }
            // verify required parameter 'repo' is not null or undefined
            if (repo === null || repo === undefined) {
                throw new RequiredError('repo','Required parameter repo was null or undefined when calling getCollaborators.');
            }
            const localVarPath = `/repos/{owner}/{repo}/collaborators`
                .replace(`{${"owner"}}`, encodeURIComponent(String(owner)))
                .replace(`{${"repo"}}`, encodeURIComponent(String(repo)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required

            // authentication tokenAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete collaborator
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {string} collaborator collaborator username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeCollaborator: async (owner: string, repo: string, collaborator: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'owner' is not null or undefined
            if (owner === null || owner === undefined) {
                throw new RequiredError('owner','Required parameter owner was null or undefined when calling removeCollaborator.');
            }
            // verify required parameter 'repo' is not null or undefined
            if (repo === null || repo === undefined) {
                throw new RequiredError('repo','Required parameter repo was null or undefined when calling removeCollaborator.');
            }
            // verify required parameter 'collaborator' is not null or undefined
            if (collaborator === null || collaborator === undefined) {
                throw new RequiredError('collaborator','Required parameter collaborator was null or undefined when calling removeCollaborator.');
            }
            const localVarPath = `/repos/{owner}/{repo}/collaborators/{collaborator}`
                .replace(`{${"owner"}}`, encodeURIComponent(String(owner)))
                .replace(`{${"repo"}}`, encodeURIComponent(String(repo)))
                .replace(`{${"collaborator"}}`, encodeURIComponent(String(collaborator)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required

            // authentication tokenAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CollaboratorsApi - functional programming interface
 * @export
 */
export const CollaboratorsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add user as a collaborator
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {string} collaborator collaborator username
         * @param {CollaboratorsCollaboratorBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addCollaborator(owner: string, repo: string, collaborator: string, body?: CollaboratorsCollaboratorBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await CollaboratorsApiAxiosParamCreator(configuration).addCollaborator(owner, repo, collaborator, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get collaborators
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCollaborators(owner: string, repo: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await CollaboratorsApiAxiosParamCreator(configuration).getCollaborators(owner, repo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete collaborator
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {string} collaborator collaborator username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeCollaborator(owner: string, repo: string, collaborator: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await CollaboratorsApiAxiosParamCreator(configuration).removeCollaborator(owner, repo, collaborator, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CollaboratorsApi - factory interface
 * @export
 */
export const CollaboratorsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Add user as a collaborator
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {string} collaborator collaborator username
         * @param {CollaboratorsCollaboratorBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addCollaborator(owner: string, repo: string, collaborator: string, body?: CollaboratorsCollaboratorBody, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return CollaboratorsApiFp(configuration).addCollaborator(owner, repo, collaborator, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get collaborators
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCollaborators(owner: string, repo: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return CollaboratorsApiFp(configuration).getCollaborators(owner, repo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete collaborator
         * @param {string} owner owner of the repository
         * @param {string} repo name of the repository
         * @param {string} collaborator collaborator username
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeCollaborator(owner: string, repo: string, collaborator: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return CollaboratorsApiFp(configuration).removeCollaborator(owner, repo, collaborator, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CollaboratorsApi - object-oriented interface
 * @export
 * @class CollaboratorsApi
 * @extends {BaseAPI}
 */
export class CollaboratorsApi extends BaseAPI {
    /**
     * 
     * @summary Add user as a collaborator
     * @param {string} owner owner of the repository
     * @param {string} repo name of the repository
     * @param {string} collaborator collaborator username
     * @param {CollaboratorsCollaboratorBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollaboratorsApi
     */
    public async addCollaborator(owner: string, repo: string, collaborator: string, body?: CollaboratorsCollaboratorBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return CollaboratorsApiFp(this.configuration).addCollaborator(owner, repo, collaborator, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get collaborators
     * @param {string} owner owner of the repository
     * @param {string} repo name of the repository
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollaboratorsApi
     */
    public async getCollaborators(owner: string, repo: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return CollaboratorsApiFp(this.configuration).getCollaborators(owner, repo, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete collaborator
     * @param {string} owner owner of the repository
     * @param {string} repo name of the repository
     * @param {string} collaborator collaborator username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollaboratorsApi
     */
    public async removeCollaborator(owner: string, repo: string, collaborator: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return CollaboratorsApiFp(this.configuration).removeCollaborator(owner, repo, collaborator, options).then((request) => request(this.axios, this.basePath));
    }
}
