/* 
 * DagsHub API
 *
 * This API provides a way to retrive & interact with data about DagsHub repositories, users, issues, webhooks and more. The API is also used by the [DagsHub Direct Data Access streaming client](https://github.com/DagsHub/client) to stream content from a repository for easier and faster training. 
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using dagshub_api.Client;
using dagshub_api.Model;

namespace dagshub_api.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IStorageIntegrationsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List contents in the path
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>Files1</returns>
        Files1 GetBucketContent (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null);

        /// <summary>
        /// List contents in the path
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>ApiResponse of Files1</returns>
        ApiResponse<Files1> GetBucketContentWithHttpInfo (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null);
        /// <summary>
        /// Get file in the bucket
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns></returns>
        void GetBucketFile (string owner, string repo, string protocol, string bucket, string path);

        /// <summary>
        /// Get file in the bucket
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GetBucketFileWithHttpInfo (string owner, string repo, string protocol, string bucket, string path);
        /// <summary>
        /// List integrated storages in the repository
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>Integration</returns>
        Integration GetBuckets (string owner, string repo);

        /// <summary>
        /// List integrated storages in the repository
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>ApiResponse of Integration</returns>
        ApiResponse<Integration> GetBucketsWithHttpInfo (string owner, string repo);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// List contents in the path
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>Task of Files1</returns>
        System.Threading.Tasks.Task<Files1> GetBucketContentAsync (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null);

        /// <summary>
        /// List contents in the path
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>Task of ApiResponse (Files1)</returns>
        System.Threading.Tasks.Task<ApiResponse<Files1>> GetBucketContentAsyncWithHttpInfo (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null);
        /// <summary>
        /// Get file in the bucket
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GetBucketFileAsync (string owner, string repo, string protocol, string bucket, string path);

        /// <summary>
        /// Get file in the bucket
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetBucketFileAsyncWithHttpInfo (string owner, string repo, string protocol, string bucket, string path);
        /// <summary>
        /// List integrated storages in the repository
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>Task of Integration</returns>
        System.Threading.Tasks.Task<Integration> GetBucketsAsync (string owner, string repo);

        /// <summary>
        /// List integrated storages in the repository
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>Task of ApiResponse (Integration)</returns>
        System.Threading.Tasks.Task<ApiResponse<Integration>> GetBucketsAsyncWithHttpInfo (string owner, string repo);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class StorageIntegrationsApi : IStorageIntegrationsApi
    {
        private dagshub_api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StorageIntegrationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StorageIntegrationsApi(String basePath)
        {
            this.Configuration = new dagshub_api.Client.Configuration { BasePath = basePath };

            ExceptionFactory = dagshub_api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StorageIntegrationsApi"/> class
        /// </summary>
        /// <returns></returns>
        public StorageIntegrationsApi()
        {
            this.Configuration = dagshub_api.Client.Configuration.Default;

            ExceptionFactory = dagshub_api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StorageIntegrationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StorageIntegrationsApi(dagshub_api.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = dagshub_api.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = dagshub_api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public dagshub_api.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public dagshub_api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// List contents in the path 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>Files1</returns>
        public Files1 GetBucketContent (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null)
        {
             ApiResponse<Files1> localVarResponse = GetBucketContentWithHttpInfo(owner, repo, protocol, bucket, path, includeSize, limit, fromToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List contents in the path 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>ApiResponse of Files1</returns>
        public ApiResponse< Files1 > GetBucketContentWithHttpInfo (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null)
        {
            // verify the required parameter 'owner' is set
            if (owner == null)
                throw new ApiException(400, "Missing required parameter 'owner' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'repo' is set
            if (repo == null)
                throw new ApiException(400, "Missing required parameter 'repo' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'protocol' is set
            if (protocol == null)
                throw new ApiException(400, "Missing required parameter 'protocol' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'bucket' is set
            if (bucket == null)
                throw new ApiException(400, "Missing required parameter 'bucket' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageIntegrationsApi->GetBucketContent");

            var localVarPath = "/repos/{owner}/{repo}/storage/content/{protocol}/{bucket}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (owner != null) localVarPathParams.Add("owner", this.Configuration.ApiClient.ParameterToString(owner)); // path parameter
            if (repo != null) localVarPathParams.Add("repo", this.Configuration.ApiClient.ParameterToString(repo)); // path parameter
            if (protocol != null) localVarPathParams.Add("protocol", this.Configuration.ApiClient.ParameterToString(protocol)); // path parameter
            if (bucket != null) localVarPathParams.Add("bucket", this.Configuration.ApiClient.ParameterToString(bucket)); // path parameter
            if (path != null) localVarPathParams.Add("path", this.Configuration.ApiClient.ParameterToString(path)); // path parameter
            if (includeSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include_size", includeSize)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (fromToken != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "from_token", fromToken)); // query parameter
            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }
            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBucketContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Files1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Files1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Files1)));
        }

        /// <summary>
        /// List contents in the path 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>Task of Files1</returns>
        public async System.Threading.Tasks.Task<Files1> GetBucketContentAsync (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null)
        {
             ApiResponse<Files1> localVarResponse = await GetBucketContentAsyncWithHttpInfo(owner, repo, protocol, bucket, path, includeSize, limit, fromToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List contents in the path 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">path of a folder in the repository</param>
        /// <param name="includeSize"> (optional, default to false)</param>
        /// <param name="limit">Maximum amount of items to return (optional, default to 100)</param>
        /// <param name="fromToken">Token, from which to continue iteration (optional)</param>
        /// <returns>Task of ApiResponse (Files1)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Files1>> GetBucketContentAsyncWithHttpInfo (string owner, string repo, string protocol, string bucket, string path, bool? includeSize = null, int? limit = null, string fromToken = null)
        {
            // verify the required parameter 'owner' is set
            if (owner == null)
                throw new ApiException(400, "Missing required parameter 'owner' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'repo' is set
            if (repo == null)
                throw new ApiException(400, "Missing required parameter 'repo' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'protocol' is set
            if (protocol == null)
                throw new ApiException(400, "Missing required parameter 'protocol' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'bucket' is set
            if (bucket == null)
                throw new ApiException(400, "Missing required parameter 'bucket' when calling StorageIntegrationsApi->GetBucketContent");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageIntegrationsApi->GetBucketContent");

            var localVarPath = "/repos/{owner}/{repo}/storage/content/{protocol}/{bucket}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (owner != null) localVarPathParams.Add("owner", this.Configuration.ApiClient.ParameterToString(owner)); // path parameter
            if (repo != null) localVarPathParams.Add("repo", this.Configuration.ApiClient.ParameterToString(repo)); // path parameter
            if (protocol != null) localVarPathParams.Add("protocol", this.Configuration.ApiClient.ParameterToString(protocol)); // path parameter
            if (bucket != null) localVarPathParams.Add("bucket", this.Configuration.ApiClient.ParameterToString(bucket)); // path parameter
            if (path != null) localVarPathParams.Add("path", this.Configuration.ApiClient.ParameterToString(path)); // path parameter
            if (includeSize != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include_size", includeSize)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (fromToken != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "from_token", fromToken)); // query parameter
            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }
            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBucketContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Files1>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Files1) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Files1)));
        }

        /// <summary>
        /// Get file in the bucket 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns></returns>
        public void GetBucketFile (string owner, string repo, string protocol, string bucket, string path)
        {
             GetBucketFileWithHttpInfo(owner, repo, protocol, bucket, path);
        }

        /// <summary>
        /// Get file in the bucket 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> GetBucketFileWithHttpInfo (string owner, string repo, string protocol, string bucket, string path)
        {
            // verify the required parameter 'owner' is set
            if (owner == null)
                throw new ApiException(400, "Missing required parameter 'owner' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'repo' is set
            if (repo == null)
                throw new ApiException(400, "Missing required parameter 'repo' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'protocol' is set
            if (protocol == null)
                throw new ApiException(400, "Missing required parameter 'protocol' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'bucket' is set
            if (bucket == null)
                throw new ApiException(400, "Missing required parameter 'bucket' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageIntegrationsApi->GetBucketFile");

            var localVarPath = "/repos/{owner}/{repo}/storage/raw/{protocol}/{bucket}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (owner != null) localVarPathParams.Add("owner", this.Configuration.ApiClient.ParameterToString(owner)); // path parameter
            if (repo != null) localVarPathParams.Add("repo", this.Configuration.ApiClient.ParameterToString(repo)); // path parameter
            if (protocol != null) localVarPathParams.Add("protocol", this.Configuration.ApiClient.ParameterToString(protocol)); // path parameter
            if (bucket != null) localVarPathParams.Add("bucket", this.Configuration.ApiClient.ParameterToString(bucket)); // path parameter
            if (path != null) localVarPathParams.Add("path", this.Configuration.ApiClient.ParameterToString(path)); // path parameter
            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }
            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBucketFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Get file in the bucket 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GetBucketFileAsync (string owner, string repo, string protocol, string bucket, string path)
        {
             await GetBucketFileAsyncWithHttpInfo(owner, repo, protocol, bucket, path);

        }

        /// <summary>
        /// Get file in the bucket 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <param name="protocol">protocol of the storage integration</param>
        /// <param name="bucket">name and prefix of the bucket integration</param>
        /// <param name="path">The content path</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GetBucketFileAsyncWithHttpInfo (string owner, string repo, string protocol, string bucket, string path)
        {
            // verify the required parameter 'owner' is set
            if (owner == null)
                throw new ApiException(400, "Missing required parameter 'owner' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'repo' is set
            if (repo == null)
                throw new ApiException(400, "Missing required parameter 'repo' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'protocol' is set
            if (protocol == null)
                throw new ApiException(400, "Missing required parameter 'protocol' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'bucket' is set
            if (bucket == null)
                throw new ApiException(400, "Missing required parameter 'bucket' when calling StorageIntegrationsApi->GetBucketFile");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling StorageIntegrationsApi->GetBucketFile");

            var localVarPath = "/repos/{owner}/{repo}/storage/raw/{protocol}/{bucket}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (owner != null) localVarPathParams.Add("owner", this.Configuration.ApiClient.ParameterToString(owner)); // path parameter
            if (repo != null) localVarPathParams.Add("repo", this.Configuration.ApiClient.ParameterToString(repo)); // path parameter
            if (protocol != null) localVarPathParams.Add("protocol", this.Configuration.ApiClient.ParameterToString(protocol)); // path parameter
            if (bucket != null) localVarPathParams.Add("bucket", this.Configuration.ApiClient.ParameterToString(bucket)); // path parameter
            if (path != null) localVarPathParams.Add("path", this.Configuration.ApiClient.ParameterToString(path)); // path parameter
            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }
            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBucketFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// List integrated storages in the repository 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>Integration</returns>
        public Integration GetBuckets (string owner, string repo)
        {
             ApiResponse<Integration> localVarResponse = GetBucketsWithHttpInfo(owner, repo);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List integrated storages in the repository 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>ApiResponse of Integration</returns>
        public ApiResponse< Integration > GetBucketsWithHttpInfo (string owner, string repo)
        {
            // verify the required parameter 'owner' is set
            if (owner == null)
                throw new ApiException(400, "Missing required parameter 'owner' when calling StorageIntegrationsApi->GetBuckets");
            // verify the required parameter 'repo' is set
            if (repo == null)
                throw new ApiException(400, "Missing required parameter 'repo' when calling StorageIntegrationsApi->GetBuckets");

            var localVarPath = "/repos/{owner}/{repo}/storage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (owner != null) localVarPathParams.Add("owner", this.Configuration.ApiClient.ParameterToString(owner)); // path parameter
            if (repo != null) localVarPathParams.Add("repo", this.Configuration.ApiClient.ParameterToString(repo)); // path parameter
            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }
            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBuckets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Integration>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Integration) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Integration)));
        }

        /// <summary>
        /// List integrated storages in the repository 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>Task of Integration</returns>
        public async System.Threading.Tasks.Task<Integration> GetBucketsAsync (string owner, string repo)
        {
             ApiResponse<Integration> localVarResponse = await GetBucketsAsyncWithHttpInfo(owner, repo);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List integrated storages in the repository 
        /// </summary>
        /// <exception cref="dagshub_api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="owner">owner of the repository</param>
        /// <param name="repo">name of the repository</param>
        /// <returns>Task of ApiResponse (Integration)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Integration>> GetBucketsAsyncWithHttpInfo (string owner, string repo)
        {
            // verify the required parameter 'owner' is set
            if (owner == null)
                throw new ApiException(400, "Missing required parameter 'owner' when calling StorageIntegrationsApi->GetBuckets");
            // verify the required parameter 'repo' is set
            if (repo == null)
                throw new ApiException(400, "Missing required parameter 'repo' when calling StorageIntegrationsApi->GetBuckets");

            var localVarPath = "/repos/{owner}/{repo}/storage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (owner != null) localVarPathParams.Add("owner", this.Configuration.ApiClient.ParameterToString(owner)); // path parameter
            if (repo != null) localVarPathParams.Add("repo", this.Configuration.ApiClient.ParameterToString(repo)); // path parameter
            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }
            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBuckets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Integration>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Integration) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Integration)));
        }

    }
}
